### ISSUE TITLE
Attempt to copy redmart

### ISSUE THREAD

**Issue by caalberts** [caalberts/wdi-sg-playground#1]

**Comment by cbas** [comment]
Poor @cseb :sob: 

You rang?

**Comment by cbas** [comment]
This was a nice effort :) Not sure you still want me to review now but would highlight that `&` needs to be escaped in HTML (and XML) as `&amp;` since it's a special character.

https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
